name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker Images'
        required: true
        default: 'alpine-glibc'
        type: choice
        options:
        - alpine-glibc
        - anyproxy
        - kaillerasrv
        - snell

jobs:
  push-to-docker-hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: tiny656/${{ inputs.image }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./${{ inputs.image }}/.
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  send-telegram-notification:
    runs-on: ubuntu-latest
    needs: [push-to-docker-hub]
    if: always()
    steps:
    - name: 'Send telegram notification'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          repository: ${{ github.event.repository.name }}
          github.ref: ${{ github.ref }}
          action: #${{ github.run_number}} ${{ github.workflow }}
          status: ${{ needs.push-to-docker-hub.result }}